### ISSUE TITLE
Improve django admin with Unfold

### ISSUE THREAD

**Issue by perepicornell** [Show-your-Heart/ShowYourHeart#3]
The [Django Unfold](https://github.com/unfoldadmin/django-unfold) library is *a theme for Django admin that incorporates common best practices for building full-fledged admin areas. It is designed to work on top of the default administration provided by Django.*.

It's made with TailwindCSS and AlpineJS.

We (Codi Cooperatiu) didn't try it yet but it was a future improvement for our boilerplate.
It might be worth including it now that we start the project to avoid having to adapt many things later on.

Its licence is MIT.

Tasks:

- [ ] Set it up in a branch and try its features to make sure there's no red flag against using it. [This video](https://www.youtube.com/watch?v=kkxAVubUOj8) can help.
- [ ] Make sure that the default admin areas keep working fine. User's, groups and permissions, Constance, changelog, Sites...
- [ ] Add the relevant information in the readme.

**Comment by silviaDabne** [comment]
PR https://github.com/Show-your-Heart/ShowYourHeart/pull/6
